---
spring:
  profiles:
    group:
      development:
        - common
        - development_database
        - redis_database
        - mongo_database
        - port_8080
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: development_database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(5VmlmJzwK8Wl0YZ+08bElqi4AmerTFbfqCle6s/ucKDAiR2ckXXbWsXi7hfXkoe7MbwGk6SLi9UgJerCcws7Oq18eC3Co71RodeVBajFtL0l0Eb7yPEBUVsYM9PCm+vPjRHZ6MZ0DrTwb69PwqVzXRgMKH6BaAS4LI789qkO/S2gKdbMNKVWGa+Ne8D7z6sW)
    username: ENC(Wmdoe6sX+spc2raHZtOCtw==)
    password: ENC(IUVsZMmnF+rgf67lv+IS7Yi+lSWjjABmtHjsjcfIgho=)
---
spring:
  config:
    activate:
      on-profile: redis_database
  data:
    redis:
      host: ENC(Cgkhtl5xSuIYpZnuNHl9L4DX8FPC9Nmt)
      port: 6379
      password: ENC(DOf5N+J7yOd9alJSOQpnznXVO5finZ3Rf0xjPNyo4lQ=)
---
spring:
  config:
    activate:
      on-profile: mongo_database
  data:
    mongodb:
      host: ENC(KBrZKlr9InMEm8d7jyt7nHk30/9EU2nlLRcqxaMZEu4=)
      port: 27017
      database: ENC(C3tpIZlYiC8I7crNUf5mAA==)
      username: ENC(TBH7CAtg639UJAR2SOEIOQ==)
      password: ENC(ol8kpyq+EI8yu1NyrKqowHVDfef1+6BmIkqg7Cs5HF0=)
      authentication-database: ENC(naViBM7D1MZn95JdhBiJrw==)
---
spring:
  config:
    activate:
      on-profile: port_8080
server:
  port: 8080
---
jasypt:
  encryptor:
    naver:
      clova:
        key: ENC(/4gocWtV/BmAvU7+80AeceqYsDqVO3ij/w6vMn6dhDuzzOVg8DFsc/vmc0BJmlRC)
        invokeurl: ENC(tRYnWsnPcp3mr7VJ8yN00HOzyigqTxhV5l2FYkifWRH2pYJdIEBDpS9B9ixXxk9wNmChPk99u6zxbhG65vEqVda5E9ICosn7tH9RsAsXwY3O0mamNC9Mv53cNGUCJGJdoUsHq2oL3fc+UMhs1XBsjDJ1/c8gpN9J3y6wM0ltqoA=)
---
jasypt:
  encryptor:
    aiurl: ENC(S5SsEvmX4X7ncHUDkHz5OJMVfy9wotQhzIz84ER28YKENkB7CNSgQw==)
---
cloud:
  aws:
    s3:
      bucket: ENC(UPXLV475FTxy+qaL4JpyCHO/oxzrFepz)
    credentials:
      access-key: ENC(Dxhdvpc6TZaCwug4ytpOBrpGUkS3TYkCJm4G4emtVig=)
      secret-key: ENC(jPqz3lNrAKBn2gX24FwSKF7EEyTREF17Zq0zMBgwsSkLu3TXTCJI6SYfoaCdVceLKDnDYYqpVM4=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
---

logging:
  level:
    com.d101.frientree : info
    org.springframework.security: trace

---
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ENC(z1j1Nk1W56xl4DmPRzueB7l/dVzCcNQYkaDFYhWklH8=)
    password: ENC(NFoW/7TREdbJ07Lvgu2y9G+i2+Lc+ztu1K9a3+7gFG8=)
    properties:
      mail:
        smtp:
         auth: true
         starttls:
           enable: true
         mime:
           charset: UTF-8
         transport:
           protocol: smtp
         debug: true
