---
spring:
  profiles:
    group:
      development:
        - common
        - development_database
        - redis_database
        - port_8080
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: development_database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(5VmlmJzwK8Wl0YZ+08bElqi4AmerTFbfqCle6s/ucKDAiR2ckXXbWsXi7hfXkoe7MbwGk6SLi9UgJerCcws7Oq18eC3Co71RodeVBajFtL0l0Eb7yPEBUVsYM9PCm+vPjRHZ6MZ0DrTwb69PwqVzXRgMKH6BaAS4LI789qkO/S2gKdbMNKVWGa+Ne8D7z6sW)
    username: ENC(Wmdoe6sX+spc2raHZtOCtw==)
    password: ENC(IUVsZMmnF+rgf67lv+IS7Yi+lSWjjABmtHjsjcfIgho=)
---
spring:
  config:
    activate:
      on-profile: redis_database
  data:
    redis:
      host: ENC(Cgkhtl5xSuIYpZnuNHl9L4DX8FPC9Nmt)
      port: 6379
      password: ENC(DOf5N+J7yOd9alJSOQpnznXVO5finZ3Rf0xjPNyo4lQ=)
---
spring:
  config:
    activate:
      on-profile: port_8080
server:
  port: 8080
---

logging:
  level:
    com.d101.frientree : info
    org.springframework.security: trace

---
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ssafytestgcp@gmail.com
    password: vqtoyjvgcrhapgol
    properties:
      mail:
        smtp:
         auth: true
         starttls:
           enable: true
         mime:
           charset: UTF-8
         transport:
           protocol: smtp
         debug: true
