---
spring:
  profiles:
    group:
      development:
        - common
        - development_database
        - redis_database
        - port_8080
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: development_database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(5VmlmJzwK8Wl0YZ+08bElqi4AmerTFbfqCle6s/ucKDAiR2ckXXbWsXi7hfXkoe7MbwGk6SLi9UgJerCcws7Oq18eC3Co71RodeVBajFtL0l0Eb7yPEBUVsYM9PCm+vPjRHZ6MZ0DrTwb69PwqVzXRgMKH6BaAS4LI789qkO/S2gKdbMNKVWGa+Ne8D7z6sW)
    username: ENC(Wmdoe6sX+spc2raHZtOCtw==)
    password: ENC(IUVsZMmnF+rgf67lv+IS7Yi+lSWjjABmtHjsjcfIgho=)
---
spring:
  config:
    activate:
      on-profile: redis_database
  datasource:
    #    url: jdbc:mysql://common-project-database.crcie0cgjdrg.ap-northeast-2.rds.amazonaws.com:3306/frientree?serverTimezone=Asia/Seoul&useSSL=false
    url: jdbc:mysql://localhost:3306/frientree
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234!
---
spring:
  config:
    activate:
      on-profile: port_8080
server:
  port: 8080
---

logging:
  level:
    com.d101.frientree : info
    org.hibernate.SQL: trace
    org.springframework.security: trace
    com.example.demo.JwtCheckFilter: DEBUG
