server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://common-project-database.crcie0cgjdrg.ap-northeast-2.rds.amazonaws.com:3306/frientree?serverTimezone=Asia/Seoul&useSSL=false
    url: jdbc:mysql://localhost:3306/frientree
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234!
#    password: developer101project

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  profiles:
    group:
      development:
        - common
        - development_database
        - port_8080
      production-set1:
        - common
        - production_database
        - port_9001
      production-set2:
        - common
        - production_database
        - port_9002
---
spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:mysql://common-project-database.crcie0cgjdrg.ap-northeast-2.rds.amazonaws.com:3306/frientree?serverTimezone=Asia/Seoul&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: developer101project
---
spring:
  config:
    activate:
      on-profile: development_database
  datasource:
    url: jdbc:mysql://common-project-database.crcie0cgjdrg.ap-northeast-2.rds.amazonaws.com:3306/frientree?serverTimezone=Asia/Seoul&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: developer101project
---
spring:
  config:
    activate:
      on-profile: production_database
  datasource:
    url: jdbc:mysql://common-project-database.crcie0cgjdrg.ap-northeast-2.rds.amazonaws.com:3306/frientree?serverTimezone=Asia/Seoul&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: developer101project
---
spring:
  config:
    activate:
      on-profile: port_8080
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: port_9001
server:
  port: 9001
---
spring:
  config:
    activate:
      on-profile: port_9002
server:
  port: 9002
---



#logging:
#  level:
#    com.project.awesomegroup : info

logging:
  level:
    org.hibernate.SQL: trace
    org.springframework.security: trace
    com.project.awesomegroup : info
    com.example.demo.JwtCheckFilter: DEBUG