name: New PR
run-name: ${{ github.actor }} is testing out New PR 🚀
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run reviewdog
        uses: ScaCap/action-ktlint@master
        with:
            github_token: ${{ secrets.SECRET_GITHUB }}
            reporter: github-pr-review

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Access BASE_URL
        run: |
            echo "BASE_URL=${{ secrets.BASE_URL }}" > local.properties
        shell: bash

      - name: Access NAVER_LOGIN_CLIENT_ID
        run: |
            echo "NAVER_LOGIN_CLIENT_ID=${{ secrets.NAVER_LOGIN_CLIENT_ID }}" >> local.properties
        shell: bash

      - name: Access NAVER_LOGIN_CLIENT_SECRET
        run: |
            echo "NAVER_LOGIN_CLIENT_SECRET=${{ secrets.NAVER_LOGIN_CLIENT_SECRET }}" >> local.properties
        shell: bash

      - name: Access NAVER_LOGIN_CLIENT_NAME
        run: |
            echo "NAVER_LOGIN_CLIENT_NAME=${{ secrets.NAVER_LOGIN_CLIENT_NAME }}" >> local.properties
        shell: bash

      - name: Check local.properties
        run: cat local.properties
        shell: bash

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
        shell: bash

      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Compile
        run: ./gradlew assembleDebug
